### ISSUE TITLE
how to use acknowledgeSystemAlert in swift

### ISSUE THREAD

**Issue by JohnJGL** [kif-framework/KIF#1025]
I'm new to KIF, and I‘m using swift 4 to write my test case, I found acknowledgeSystemAlert can not be used like OC( [tester acknowledgeSystemAlert]). So, how to use acknowledgeSystemAlert in swift, or how to dismiss system alert in swift test case?
thanks!

**Comment by justinseanmartin** [comment]
Take a look here for an example of using KIF from Swift code: https://github.com/kif-framework/KIF/blob/master/Documentation/Examples/Testable%20Swift/Testable%20SwiftTests/SimpleSwiftTest.swift

You should be able to do `viewTester().acknowledgeSystemAlert()`.

That said, my general advice is to not rely on this method, as it relies on private methods from Apple's UIAutomation framework behind the scenes. It is hard to trace and diagnose when it isn't working as expected and more prone to break in future Xcode releases. 

My suggestion would be to avoid code that causes the system alert to be popped up. See my comment in #979 for more context.

**Comment by JohnJGL** [comment]
avoid system alert to be popped up may needs to deal with many problems, for example: get private api for different authorization, iCloud backup alert, low battery alert, iOS system update alert, I'm not sure if we can find way to avoid all those alert to be popped up

**Comment by mikelupo** [comment]
For the upgrade pop ups I avoid them by connecting the iOS device by WiFi. I set up a privoxy proxy server that blacklists the Apple addresses. If you do decide to use a proxy make sure you use a high non-standard port number for it and then white list requests access to it so that hackers can’t connect. Else it will have over 20,000 connections in just a few hours as happened to me.

**Comment by JohnJGL** [comment]
@mikelikespie  This sounds incredable, I will try this. Thank you verry much!
