### ISSUE TITLE
XCTestCase-KIFAdditions.m and UIApplication-KIFAdditions.m uses method_exchangeImplementations() instead of method_setImplementation()

### ISSUE THREAD

**Issue by kamal-mann** [kif-framework/KIF#1031]
Recently I was reading up on better (correct) way of swizzling a method and found it's better to use method_setImplementation() instead of method_exchangeImplementations(). More details on this can be found [here.](https://blog.newrelic.com/2014/04/16/right-way-to-swizzle/)

Places where it is getting used:

1. [XCTestCase-KIFAdditions.m](https://github.com/kif-framework/KIF/blob/bcb58d0419cfaefe286f3df1c8618bac43b45921/Additions/XCTestCase-KIFAdditions.m#L24)
2. [UIApplication-KIFAdditions.m](https://github.com/kif-framework/KIF/blob/b52c375f649dfb852a73981d43b05f1edf1fa1dd/Additions/UIApplication-KIFAdditions.m#L304)

**Comment by justinseanmartin** [comment]
Can you explain more about why you think one is better than the other? 

Method implementation exchanging is necessary in this case, because the sizzled method actually needs to invoke the original implementation. 

This can be seen here for example:
https://github.com/kif-framework/KIF/blob/bcb58d0419cfaefe286f3df1c8618bac43b45921/Additions/XCTestCase-KIFAdditions.m#L103
