### ISSUE TITLE
How to load a specific view controller in KIF tests?

### ISSUE THREAD

**Issue by faisalazeez** [kif-framework/KIF#1037]
Currently, am navigating through all view controller to reach a specific view controller for testing. But is there a way that I can load a specific view controller for testing that particular page?

**Comment by mikelupo** [comment]
I’m not sure i understand your question. 
Does the user of the app you’re testing have access to this UI using regular navigation methods.? That being a button tap, swipe, etc...if so, then it’s easy with KIF. If you’re trying to load a UI programmatically, you can do that too I suppose, but that’s not something I do in my testing and can’t accurately answer.

**Comment by justinseanmartin** [comment]
@faisalazeez - Your tests can grab the app delegate via `[[UIApplication sharedApplication] delegate]` and call whatever methods you want on that if you really would like to be very white box with your test approach. You could alternatively expose private APIs for your tests to jump to specific parts of the app or load particular view controllers as you'd like.

We do this for resetting app state and jumping directly to the logged in screen rather than going through the UI to get logged in over and over again (faster and less error prone).

This isn't a KIF specific question however. I'd recommend asking this on StackOverflow.
