### ISSUE TITLE
KIF 3.7.1 does not tap on view that is off screen

### ISSUE THREAD

**Issue by LMojica** [kif-framework/KIF#1062]
I am currently using KIF 3.6.0, and everything has been working fine. I upgraded to 3.7.1 and my tests started failing. Upon investigating the failures, I noticed that KIF was no longer tapping on views that were off screen. For example, one of my tests taps on a button that is at the top of the screen, and only about 1/4 of the button is visible. KIF 3.6.0 was able to tap on this button with no problem using `KIFUITestActor.tapView(withAccessibilityLabel:)`.  KIF 3.7.1 fails the test with the error: `The step timed out after 45.00 seconds: View is not tappable`. I downgraded back to KIF 3.6.0 and can confirm that my tests are passing again.

I also attempted to using `KIFUIViewTestActor` instead while I was on KIF 3.7.1 by calling `KIFUIViewTestActor.usingLabel(label).tap()`, and it also fails.

I am using Xcode 9.2 and running tests on an iOS 11.2 iPhone 7 Simulator.

I checked recent commits and I think this one is the one that changed the behavior https://github.com/kif-framework/KIF/commit/d006865ef81b09e246a8dfe69254ea8235695084#diff-566e05ba4bd3dbb38b960804e911a25aR174. Is it possible that this doesn't take into account any view elements that are only partially visible?

**Comment by justinseanmartin** [comment]
Does the partially offscreen element require being scrolled in order to be tapped successfully? The only elements that shouldn't be scrolled are ones that are already visible on the screen. Maybe you could help with understanding why the element passes the check `view.isVisibleInWindowFrame` in `UIAccessibilityElement-KIFAdditions.m`, but is failing the tappability check for `[KIFUITestActor tapAccessibilityElement:inView:]`?

I needed to make the changes in d006865 in order to get the tests to pass on iOS11, as it appeared that the "swipe to delete" behavior was broken in iOS11. I figured that there was a possibility that this might lead to other regressions, but would require some debugging to sort out the edge cases of who was relying on that scrolling and why.

Any help is appreciated in understanding the issue in more detail to have a repro. The tests in the regression suite all passed, so the change seemed relatively safe to make.

FYI - Under the hood KIFUITestActor and KIFUIViewTestActor should be doing the same thing, just the latter's API is more flexible/composable.

**Comment by dflems** [comment]
I'm also seeing this in the latest release. In this case, there's a vertical collection view containing scrollable horizontal collection views. The intended view is in the third horizontal cell in the last vertical cell. Around 1/4 of the view is on-screen if you were to scroll down to it. KIF seems to scroll down to the correct vertical cell, but then seems to scroll *back* up the way it came. It then successfully returns the view, but it's no longer on-screen.

I might be able to create a reproducible scenario for this. It fails in a similar way in a few of our tests. There's always scrolling involved and a view that is near the edge of the screen.

**Comment by dflems** [comment]
@justinseanmartin 👋

**Comment by justinseanmartin** [comment]
@dflems - FYI - I just closed #1070, because I think we have better fixes with #1102 (merged) and #1103 (out for PR, but seems to be working?). If you want to give the branch `harleyjcooper:harley/kif-fix-table-scrolling`, would be good to have another data point if this is making stuff better.
