### ISSUE TITLE
KIFUITestActor setSwitchOn always failed in some scenario

### ISSUE THREAD

**Issue by cruisediary** [kif-framework/KIF#1063]
Hi I have a issue when using KIF to test Acceptance Test

scenario is

User tap switch on but if viewModel check business logic should render UISwitch off
then viewModel request to viewController displaying UISwitch off
so when user switch on but UI updated to switch off by viewModel

in `KIFUITestActor.m : 847 ~ 950` this failWithError always occur because before line wait 0.5 intervals 
if switch isOn state changed during 0.5 intervals then always fail 

````objectiveC
    // We gave it our best shot.  Fail the test.
    if (switchView.isOn != switchIsOn) {
        [self failWithError:[NSError KIFErrorWithFormat:@"Failed to toggle switch to \"%@\"; instead, it was \"%@\"", switchIsOn ? @"ON" : @"OFF", switchView.on ? @"ON" : @"OFF"] stopTest:YES];
    }
````

**Comment by justinseanmartin** [comment]
I generally tend to agree that the behavior of the `setSwitchOn` is probably too opinionated about expected behavior. I'd be a little wary to change the behavior due to existing consumers. The reason KIF is doing that assertion in the first place is because it isn't 100% sure that tap events are being received and handled by the appropriate control, so it wants to make sure the UI state changed.

In our tests, we have a category on `KIFUIViewTestActor` that puts more control in our own hands. It is something along the lines of:

```
@implementation KIFUIViewTestActor (UISwitch)
- (instancetype)matchingSwitchObjects;
{
    return [self usingPredicate:[NSPredicate predicateWithBlock:^BOOL(id evaluatedObject, NSDictionary *bindings) {
        return [evaluatedObject isKindOfClass:UISwitch.class];
    }]];
}
- (BOOL)isSwitchOn;
{
    @autoreleasepool {
        UISwitch *switchView = (UISwitch *)[self waitForView];
        NSAssert([switchView isKindOfClass:UISwitch.class], @"Matched an object of the wrong class for switch action: %@", NSStringFromClass(switchView.class));
        return switchView.isOn;
    }
}
@end
```

Then it can be used like: `[[[viewTester usingLabel:@"Switch Name"] matchingSwitchObjects] tap];` and `XCTAssertTrue([[[viewTester usingLabel:@"Switch Name"] matchingSwitchObjects] isSwitchOn])`. 

I haven't tested the above code, so take it with a grain of salt, but it hopefully should get you heading in the right direction.

I wouldn't want to put the code above into KIFUIViewTestActor as it is. I think it would be more appropriate on a test actor specifically tailored to only acting on switch elements and exposes actions that only make sense for switches, maybe `KIFUISwitchTestActor`. The assertion on the UIView's class should then be unnecessary, as the predicate within `matchingSwitchObjects` would always be applied. Let me know if you're interested in working on this.
