### ISSUE TITLE
Some how KIF reaches the last item in UICollectionView when tapViewWithAccessibilityLabel

### ISSUE THREAD

**Issue by thiennguyenEA** [kif-framework/KIF#1067]
To be able to lazily load more data when UICollectionView reaches the last row, I do like below:

```Objective-C
- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(nonnull NSIndexPath *)indexPath {
  MVACollectionViewCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:MVAPopularCollectionCellPrototypeIdentifier forIndexPath:indexPath];

 if (last row) {
  LOAD MORE DATA;
}
  return cell;
}
```

In UITests, I mock 20 items for the UICollectionView and it currently display 9 items which has not reached the last row.
But when UITests run any statements: tapViewWithAccessibilityLabel or waitForViewWithAccessibilityLabel, "SOME HOW" it make the UICollectionView reach the last item EVEN no scrolling down has been made. It makes LOAD MORE DATA run many times lead to very slow UITests.

**Comment by justinseanmartin** [comment]
This is actually a different issue than #491 now that I look at it. You're elements are being enumerated here to see if KIF can find a matching element to act on:
https://github.com/kif-framework/KIF/blob/e69c25e84d67301b39a1aba56f7b5b89fcf78af4/Additions/UIView-KIFAdditions.m#L296-L310

The issue is that you're loading data when being asked for a cell for a particular row. This isn't a safe assumption, as enabling VoiceOver will do the same thing to enumerate elements in a table view. Instead, you could hook `scrollViewDidScroll` or something similar which actually indicates that the view position has changed to determine if more cells should be loaded. This is not a problem in KIF.

**Comment by thiennguyenEA** [comment]
Thanks for your response!
I will try using scrollViewDidScroll.
I just wonder why KIF has to enumerate all views instead of visible views only.

**Comment by justinseanmartin** [comment]
The intent is the same as in Apple's "UI Automation" framework:
https://forums.developer.apple.com/thread/16810

Two reasons as to why from my opinion:
1. It adds complexity that needs to be managed in tests that is arguably unnecessary. Tests end up being rigid and prone to breaking if you have to keep track of the scroll position of all views in the app and have your tests take that into account for every action.
2. Table and collection views behave differently than other views, in that they only load offscreen elements on demand. The tests would behave differently when enumerating the subviews of a table/collection views than others, unless the behavior is changed to explicitly not match any offscreen elements.

At this point in time, it is pretty solid as a core assumption of the KIF framework.
