### ISSUE TITLE
怎么对第三方Facebook登录返回的系统弹窗下的两个按钮（"Cancel" 和 "Continue"）进行测试

### ISSUE THREAD

**Issue by UniqueSilence** [kif-framework/KIF#1069]
![456a37ef-11bd-446d-b8b4-7ed602694a9c](https://user-images.githubusercontent.com/24645933/40528984-70ae5346-6025-11e8-8817-c5d0597e923a.png)

**Comment by justinseanmartin** [comment]
Google Translate did a pretty good job: How to test two buttons ("Cancel" and "Continue") under the system popup window returned by a third-party Facebook login

From what I can tell, this is a system alert being popped:
https://github.com/openid/AppAuth-iOS/issues/177

The only way to interact with system alerts is to use `tester acknowledgeSystemAlertWithIndex:`, but that will only work in the simulator and not on physical devices themselves. That is because the interaction with system alerts is performed by loading UIAutomation.framework directly and using the functionality exposed by them.

My general recommendation is to stub out the code that required the system alert via swizzling or inserting an API in between your access to the system APIs that you can control. You'll have more direct control over testing different expected behaviors of the API this way. It does mean however that some portion still would require a small amount of manual testing.

PS - Some of the system API behaviors behave differently in simulator than they do on devices. For example, microphone permission is always available in the simulator instead of requiring being granted via system permissions.

**Comment by UniqueSilence** [comment]
alright，thank for your explanation,  what you is watching is En, not CN. No translation.
