### ISSUE TITLE
导航栏left-right-barButtonItem, how to test？

### ISSUE THREAD

**Issue by UniqueSilence** [kif-framework/KIF#1072]
![6ff17640-9110-497d-bff9-670aefa30f37](https://user-images.githubusercontent.com/24645933/40911040-58142df8-6820-11e8-9996-02763bb76268.png)
对于leftBarButtonItem是原生的，因为有title，所以我直接用tester().tapView(withAccessibilityLabel: "Ask")  没有问题，  而右边没有title，我给这个BarButtonItem加了accessibilityLabel，并不能实现模拟点击效果，通过 tester().tapScreen(at: CGPoint(x: SCREEN_WIDTH - 30, y: 38))，也不能实现模拟点击效果，哪位大神帮给个解决方案，【ps: if you want to travel  some place  in China, I can pick you up.】

**Comment by justinseanmartin** [comment]
Google Translate:
For the leftBarButtonItem is a native, because there is a title, so I directly use the `tester().tapView (withAccessibilityLabel: "Ask")` no problem, and there is no title on the right, I added the `accessibilityLabel` to this BarButtonItem, and can not achieve the simulation click effect, through Tester().tapScreen(at: CGPoint(x: SCREEN_WIDTH - 30, y: 38)). Can't implement the simulated click effect. Which big God will give a solution?

**Comment by justinseanmartin** [comment]
You could try using `po [UIView printViewHierarchy]` in the LLDB debugger terminal to dump the accessibility elements of the screen out. You should almost never have to resort to `tapScreen` with coordinates.

What error message did you receive when trying to tap on the `...` via the `accessibilityLabel`?
