### ISSUE TITLE
 Location Status ON/OFF using KIF

### ISSUE THREAD

**Issue by sumitghosh-tudip** [kif-framework/KIF#1110]
I am trying to automate the location update for App. I want to check whether the product is available for that location which is ON/OFF for that I am writing the test case.

I want to turn location 'ON/OFF' through automation without going to the Setting page. After turning the location ON, also able to turn OFF the location through automation.

I have a search in the KIF document but I didn't find any solution.
Please let me know if there is any possible solution/workaround for this.

**Comment by justinseanmartin** [comment]
You can't explicitly alter simulator system settings from within KIF. What you can do is swizzle the location APIs and alter their behavior for how you'd expecting how the system to behave with the location on/off. It isn't possible to test against system dialogs (such as the location permission prompt), because it is not hosted in a window in the process that the tests are running in. In order to stub the location manager APIs, you can try something like what I posted in issue #979.
