### ISSUE TITLE
CollectionView, additional willDisplayCell gets called when waiting for cell which is not visible

### ISSUE THREAD

**Issue by ElyasNaranjeeSani** [kif-framework/KIF#1123]
When waiting for a view with accessibility label which is not in `VisibleItems` of `CollectionView`, additional call to `collectionView willDisplayCell` happens. 

NOTE: As mentioned, this only happens if you ask `KIFUITestActor` to wait for a view which is not a visible cell, so KIF will need to scroll down to find it.

Here is an example in my case:

Having 
```
[tester waitForViewWithAccessibilityLabel:@"Cell at the bottom of the view"];
```
Results in two calls to `collectionView willDisplayCell`

1- First call
![Screenshot 2019-10-04 at 15 45 19](https://user-images.githubusercontent.com/4579208/66213862-def1ab00-e6c0-11e9-9304-07f788d8aaa0.png)

2- And second call
![Screenshot 2019-10-04 at 15 45 32](https://user-images.githubusercontent.com/4579208/66213891-ea44d680-e6c0-11e9-8d78-2c82aa6e4101.png)

FYI: In my `CollectionView`, I only have one `ReloadData`.
This never happens if I ask tester to wait for a cell which is visible.  

NOTE: Additional `willDisplayCell` happens for other cells too and not only the one your are waiting for.

**Comment by justinseanmartin** [comment]
This will be called first on a cell that is created for the offscreen element for this code:
https://github.com/kif-framework/KIF/blob/master/Additions/UIView-KIFAdditions.m#L323-L326

If a matching element is found for the matching predicate, then it we perform the actual scroll to that visible region of the screen, triggering it a second time:
https://github.com/kif-framework/KIF/blob/master/Additions/UIView-KIFAdditions.m#L342

Is this causing problems for some reason? I'd guess the same behavior could happen if you scroll the cell onto screen, then off screen, then back onto screen.

**Comment by ElyasNaranjeeSani** [comment]
@justinseanmartin Thanks for the reply. 

It makes it impossible to have **_happened  only once_** verifications in `CollectionView`, if you are verifying sth which is expected to happen **only once** in `willDisplayCell`. 

Unless there is another way of scrolling all the way down in `CollectionView` using `KIF` that I'm not aware of, instead of calling `waitForViewWithAccessibilityLabel` for an element at the bottom.

**Comment by justinseanmartin** [comment]
You could use `swipeInDirection:`, but I generally wouldn't recommend it, as it will do an animated scroll,  and may or may not stop in a precise location. It will also not be exactly the same scroll distance on different device types.

Can you give a little more detail about the action that should only trigger once and that needs to be performed in `willDisplayCell`? Won't this get called more than once if it is scrolled into view, then out of view, then back into view?

**Comment by justinseanmartin** [comment]
Oh, I think I see what you're saying. It isn't that it is a problem that it could be invoked more than once. You'd just like to be able to verify that it happens exactly once when the element is scrolled into view. I don't have a good answer off the top of my head, aside from using the `swipe` action instead, but it is also a bit hacky.

**Comment by ElyasNaranjeeSani** [comment]
Yes the challenge is verifying `happened only once` scenario.
`swipe` is a bit hacky as you mentioned too, the thing it was fine previously using KIF but the issue started to happen when we upgraded KIF from `3.6.0` to latest.

**Comment by ElyasNaranjeeSani** [comment]
i.e. In our case we have horizontal `CollectionView` in vertical `CollectionView`, and `willDisplayCell` logs that "user will see cell". 

Using `waitForViewWithAccessibilityLabel` we were able to verify this log is recorded **exactly once** by scrolling to the last item of each `CollectionView` (calling `waitForViewWithAccessibilityLabel` was automatically scrolling for us and it does now too). 
But latest KIF `willDisplayCell` gets called more than what it should so this verification is not possible anymore.

**Comment by justinseanmartin** [comment]
The reason the call to `willDisplayCell:` was added for items that are offscreen is mentioned briefly in in the PR (#1106). In more detail, some code may mutate the view/accessibility hierarchy during the call to `willDisplayCell:`, which prevents matching and scrolling that offscreen element into view. Adding the call to `willDisplayCell:` to ensure the accessibility for the offscreen element is updated before checking to see if it matches the search predicate.

I'm not sure of a clean path to make both cases work without something custom. We could plumb something like a `matchingOptions` parameter through which determines whether or not to call `willDisplayCell:` on the collection view cells. This seems like it'll make the framework harder to reason about though, and would be very specialized. 

It seems like that "user will see cell" logging code is going to get triggered for each action that interacts with that screen, regardless of whether it is trying to interact with that element or not. This could also potentially be avoided by adding another `matchingOptions` for whether or not we should even be attempting to match offscreen elements. This feels like another pretty niche matching option though, because most of the time, developers want this to fade to the background.

I think my recommendation would be to use the swipe actions until the element that you're expecting to be onscreen is visible, because that is the closest approximation of the user behavior that you're trying to mimic. The implicit scrolling to match against offscreen elements in KIF necessitates some behavior that isn't necessarily how you'd expect the app to behave for a real user.

I'd be curious how XCUITest behaves for a simple reproduction of the scenario. I'd guess they probably behave the same way as KIF does, but it is possible they don't call `willDisplayCell:` for offscreen elements when attempting to find a matching element.

**Comment by ElyasNaranjeeSani** [comment]
I see. What #1106 is concerning is also very valid. 

As you mentioned I'm also not sure what could be the a clean path for make both work. 
I can try `swipe` but that would be a bit hacky as well. 

So maybe we can re-visit this, if more requests come from integrators and I close the issue for now.
Thanks for your time and the clarifications on this.
