### ISSUE TITLE
KIF expects UITextView to become first responder

### ISSUE THREAD

**Issue by iwasrobbed** [kif-framework/KIF#302]
If you place a `UIGestureRecognizer` on a `UITextView` with editable set to NO and then have KIF tap that view, KIF will throw an exception since it expects the `UITextView` to become first responder.

Code reference: https://github.com/kif-framework/KIF/blob/master/Classes/KIFUITestActor.m#L176

Error thrown: `Failed to make the view into the first responder`

Is there a specific reason that the view has to become first responder or could this be left out?

**Comment by applequist** [comment]
Hi, 

I have the same issue with trying to enter text into a textfield more than once, e.g. test login with invalid credentials then with valid ones: when trying to enter text in the username field the second time I get the same error: Failed to make the view into first responder.

When looking at the code I ended in KIFUITestActor#tapAccessibilityElement:inView:. This method taps the view and then expect the following condition to be true:
! [view canBecomeFirstResponder] || [view isDescendantOfFirstResponder]

The negated first term seems odd: if KIF want to make tapped view become first responder why throw an exception if the view CAN become first responder BUT is NOT a descendant of the current first responder ?

While debugging, I tested the terms:
(lldb) po [view canBecomeFirstResponder]
true

(lldb) po [view isDescendantOfFirstResponder]
NO

Sorry if I'm totally off the point, I'm new to iOS and KIF

Brieuc

**Comment by phatmann** [comment]
I will work on a fix.

**Comment by Ahmed-Ali** [comment]
I had similar issue, and turns out that I had made a very naive mistake.
I have an "Edit profile" screen, and the view controller the delegate for if the fields, by mistake I put the following delegate method implementation
- (BOOL)textFieldShouldBeginEditing:(UITextField *)textField {
    [self.view endEditing:YES];
    if(textField == self.birthdateField){
        return NO;
    }
    
    return YES;
}


As you can see, once any text field tries to become first responder, the first line of my method will resign it. Somehow, in the normal target it did not cause an issue; but it caused the issue when trying to implement the UI testing.

**Comment by phatmann** [comment]
@applequist: is @Ahmed-Ali's post relevant to your situation?
