### ISSUE TITLE
-[KIFUITestActor waitForViewWithAccessibilityLabel:] returns tableView instead of UILabel or cell

### ISSUE THREAD

**Issue by vizgueb** [kif-framework/KIF#336]
A table contains 3 UITableViewCell and each of them contains a UILabel with a different UIAccessibilityLabel.
For one cell, calling waitForViewWithAccessibilityLabel returns the proper label for others it returns the UITableView itself.
Notes:
- userInteraction is disabled on both labels.
- the hitTest on all points returns the UITableViewCellScrollView which is not the most front view because the UILabel belongs to the UITableViewCellContentView.

**Comment by edalford11** [comment]
I'm having this exact problem, except timing doesn't seem to be an issue. The cell is displayed in the view but whether I wait for 3 seconds or 0 seconds, requesting the cell with the correct accessibilityLabel keeps returning the tableView instead of the cell. Using the cellForRowAtIndexPath method as a work around to get the cell for now.

**Comment by phatmann** [comment]
Closing this since there is a workaround. I will re-open this if we can get a failing unit test in place.
