### ISSUE TITLE
tester #define is not worked in swift

### ISSUE THREAD

**Issue by cybertk** [kif-framework/KIF#421]
When integrate KIF into a swift project, tester func does not work

The idiomatic KIF 3.0 syntax for a UI test in Objective-C looks something like:

``` objc
[tester waitForTappableViewWithAccessibilityLabel:@"Welcome"];
```

According to Apple Documentation, translate to something like this in Swift:

``` swift
tester(waitForTappableViewWithAccessibilityLabel("Welcome")
```

**Comment by bmsoko** [comment]
Hello all! I've a code example project, https://github.com/tutsplus/UIAutomation-Jumblify.git, that I've been trying to add automated tests (for practicing purpose since I'm new to the iOS Automation world), and I've followed the instructions on the README, and when I build, I'm getting this error:
![buildswifterror1](https://cloud.githubusercontent.com/assets/3765964/10542340/e87dc0d6-73ed-11e5-9afa-cdea05fa3944.png)

This is the project structure, in which you'll find the header file

![swifterror2](https://cloud.githubusercontent.com/assets/3765964/10542363/170d2810-73ee-11e5-82d0-403b6907fdf4.png)


Is there any other configuration that I need to do? I've followed the CocoaPods steps!

Please help!

Thanks!!!

**Comment by CalQL8ed-K-OS** [comment]
¿are you importing the Test framework?, because you need to
