### ISSUE TITLE
An element should be "Absent" if its height constraint is set to 0

### ISSUE THREAD

**Issue by edalford11** [kif-framework/KIF#609]
waitForAbsenceOfViewWithAccessibilityLabel should not recognize elements with a height constraint of 0. Since they are not visibly on the screen, shouldn't they be absent?

**Comment by phatmann** [comment]
Can you give an example where this scenario comes into play?

**Comment by Benuuu** [comment]
If the programmer decides to hide a view from the user by collapsing its height to 0.

e.g. Consider a search button that when tapped expands to be the full width of the screen compressing anything to the side of it.

| some title | search |
Press button
|| search text field |

The title label is collapsed to a width of 0 but is no longer visible to the end user, but its visibility properties are not changed.

**Comment by Benuuu** [comment]
Similarly if the alpha level is 0 isHidden doesn't return YES.  This means the view will not be "absent"

**Comment by phatmann** [comment]
Please see the relevant discussion #516 about alpha and absence. Because a view can have zero height during an animation but still be present, I do not want to make this change because it will break existing tests. What you want to test instead of absence is "tappability". If a view with no height is considered tappable, then we have a bug we need to fix.
