### ISSUE TITLE
tapAccessibilityElement:inView: should not charge the view.isUserInteractionActuallyEnabled

### ISSUE THREAD

**Issue by Fenado** [kif-framework/KIF#625]
file:KIFUITestActor.m  line:193
KIFTestWaitCondition(view.isUserInteractionActuallyEnabled, error, @"View is not enabled for interaction");
The condition is too strong to allow the case that view.superview should handle the tap event.
I think change like this will more practical:
KIFTestWaitCondition(view.isProbablyTappable, error, @"View is not enabled for interaction");

**Comment by phatmann** [comment]
I see the problem and agree that it needs solving. However, changing to `isProbablyTappable` might cause issues, since that method calls `isTappable`, which checks that the point is in the view frame. However, the code at lines 196-207 does the same thing but using the element frame. So we might want to do the following:

1. Check if `isUserInteractionActuallyEnabled` is true. If so, continue.
2. If false, walk up the view hierarchy and see if any superviews pass the `isProbablyTappable` test.

Alternately, we might want to be checking parent accessibility elements and not parent views, checking their frames in the same manner as lines 196-207.

Lots of possibilities...all fraught with subtle changes and issues. I would welcome a pull request here :-)
