### ISSUE TITLE
OCUnit deprecation warnings

### ISSUE THREAD

**Issue by justinseanmartin** [kif-framework/KIF#644]
Is it time to entirely deprecate OCUnit support from KIF? Its been a long time now, and we're working to get warnings free in our project (including test targets).

I'd be happy to do the work if it is desirable. Just wanted to check before digging in. Thanks!

**Comment by dfed** [comment]
+1

**Comment by RoyalPineapple** [comment]
+1

**Comment by mthole** [comment]
+1!

**Comment by mokagio** [comment]
+1

**Comment by chinnawatp** [comment]
+1

**Comment by phatmann** [comment]
I feel your pain. A few thoughts here:

* You can remove the OCUnit deprecation warning by double-clicking the warning and clicking the "won't change it now" button (I forget the actual text). 
* If you install KIF via CocoaPods, OCUnit is not included by default.
* Perhaps we can find a way to separate OCUnit from the main KIF branch so that non-CocoaPods users can also forego OCUnit if they wish
* Anyone doing iOS 6 testing will need OCUnit. Since some older devices do not support iOS 7 or 8, this may be a requirement for some shops. So it may be a little premature to completely throw it overboard.
* KIF 4 (see #579) will not support OCUnit, so eventually this will be a moot point

**Comment by phatmann** [comment]
FYI, there is a new v4 branch (#646) and OCUnit support has been removed from it (705e5f3e). So we are on our way :-)
