### ISSUE TITLE
Add memory monitoring to KIF

### ISSUE THREAD

**Issue by czechboy0** [kif-framework/KIF#647]
I've been seeing issues mentioned in #515 quite a bit, so I think it might be worth trying to look deeper into the memory issues. For some reason, apps that normally consume < 50MB of memory can take > 300MB of RAM when running in KIF. Some way to record how much memory is consumed over time in KIF would be great (maybe a property inspectable in `afterEach`?) This could also be added to test failure exceptions as a value in `userInfo`. Ideally, one could turn it on and KIF would print out the memory consumed before/after each test - for better understanding of long running tests when looking at its log from a CI run.

**Comment by phatmann** [comment]
:+1:

**Comment by satchnut** [comment]
+1

**Comment by azav** [comment]
Absolutely everything leaks.  Waiting for a views, waiting for accessibility items, clearing a field, everything in KIF 3.7.7 leaks.  It leaks so much that multiple machines crash out to the login screen.  68 files with 289 tests use over a GB of memory.    I'll try to reply with the exact leaks if I can locate exactly where they are happening.

**Comment by justinseanmartin** [comment]
Thanks for reporting. If you can pause part way through a run and use the memory inspector with the malloc stack logging enabled, that would be super helpful. I'd love to hear about what objects you see sticking around in memory during the test and what call stack those were allocated with.

Is this something new in 3.7.7? If you go back to 3.7.3 (or further back), does it still exhibit the same behavior?

The one thing that I will call out from my own experience is:
1. Make sure to nil out any instance variables held by XCTestCase subclasses during tearDown/afterEach. This is pretty easy to forget to do, and isn't obvious that the behavior of the framework is to hold the test case instances in memory. More info: https://qualitycoding.org/xctestcase-teardown/
2. Be careful about which objects that you directly reference in your test cases. If you grab a pointer reference to a UIKit object that will be autoreleased without wrapping it in an `@autoreleasepool`, their lifetime may be extended to the `@autoreleasepool` lifetime for `-[XCTestCase invokeTest]` I believe.

**Comment by azav** [comment]
I created a simple case app over the weekend and ran with malloc scribble and allocation logging.  It appears that waiting for an incorrectly named accessibility item leaks as well.  I'll follow your advice, as all I was doing in my simple case tests was waiting for a view with an accessibility identifier and tapping an element with an accessibility identifier.  Now, I'm not explicitly capturing any pointer to an object, but 
it looks like strings used to specify the accessibility identifiers may be what is leaking or the autorelease pools aren't autoreleasing.  I have the memory graph file since the leaks instrument document is immense.  I'll prepare the sample and the memory graph file for you.  Thank you.

**Comment by justinseanmartin** [comment]
Couple of things:
1. You don't explicitly need to wait for an element to appear, you should just tap on the element. KIF internally spins the runloop for up to 10s waiting for the element to appear in the view hierarchy. It is possible that KIF returning the UIView element is enough to cause its lifetime to be extended? I'd have to look closely at a repro to see.
2. For `tearDown`, what I meant was if you have any instance variables being held by your test classes at any level of the subclassing hierarchy, they need to be explicitly nil'ed out in `tearDown` or the objects will be "leaked" for the lifetime of the process for that test run.

If you can send me the sample project that you're running, I can try to reproduce the results locally.

**Comment by azav** [comment]
Thanks Justin.  I can’t because it’s a corporate product and I can tell that we don’t have any locals that need to be cleared in our test cases.  As for what is allocated within the code that is run, well, it’s not trivial.  There are other problems internally on our end that sadly, KIF magnifies.  I can send Memory Graph exports though.

By magnifies, there is a case where when running the app without KIF, when we load a screen and tap on a cell, our memory usage jumps 5 MB, but when we run it within KIF, the memory usage jumps 30 MB.  From what I saw, it looks like KIF is loading every framework that could handle a text field tap.  We are not using iAD or Messages, but KIF is checking to see if the tap is happening in one of these.  Is this part of the problem?  I don’t know.   I found another that ends up with about a 90 MB allocation and I’d just love to know what’s going on there.

I did notice that when running the KIF samples as standalone apps and testing within KIF, the memory used is significantly higher when run as KIF tests.

Because of the nature of our app, I don’t know how or what I can clear to get memory back.  I’ve run leaks and heap on the memory dump from before and after large memory allocations (~30MB) but haven’t had time to dig deeper.  

I’ve split up our 300 test cases into 4 test targets, each with 20 test files, and each target takes about 600 MB to run.  For now, this is less bad than the machine rebooting while running the tests.

If I have time tomorrow, I might try disabling some library loads within KIF to see if I can eliminate some of the framework loads that our app doesn’t use.

There is some significantly powerful code in KIF.  A lot of it is beautiful.  While I’d love to understand why memory use is so high (do UI objects take up more memory?  Is it because of loading extra frameworks?  Is it both?), I need to get to a good enough solution and move back to deliverables.  

If you’d care to enlighten me about the memory internals of KIF, I’m all ears.

Thanks for your time.   
Alex Zavatone

**Comment by justinseanmartin** [comment]
I thought when you said you had a simple case, you were doing it in the context of a sample app or something simple. You could try to reproduce the issue with the test app that is contained in the KIF project, or one of the sample apps.

KIF doesn't really have a memory management model to speak of. It has no singletons, no long lived objects, and no caches. If you look at the macro definition for `tester` (or `viewTester`), it is allocating a new `KIFUITestActor` (or `KIFUIViewTestActor`) object on the stack, and that object should be destroyed when it goes out of scope. The tester objects are generally pretty lightweight though (like 80 bytes each).

The other thing that is worth mentioning is that when exceptions are thrown and caught in Objective-C, they leak memory by default unless you compile with a special clang compiler flag. You can read more about it here:
https://www.eltima.com/dev/2014/08/11/objective-c-arc-and-exceptions/

Even if your code isn't explicitly using @try/@catch blocks, XCTest as a test framework has them. It halts test execution by throwing exceptions and then catching them in `invokeTest` in order to report the test as failed and run `tearDown`. If you have tests that are known to be failing in your test suite, any objects that are allocated and supposed to be torn down between the scope where the failure occurred and the catch happens, they'll leak.

**Comment by azav** [comment]
Yes, I have done a simple case as well.  Sorry, that was Friday.  

I have seen that when an test exception happens, none of the memory is returned for the KIF operations (waiting for a tappable view) until the end when the app quits or all tests finish.  

> On Jun 24, 2019, at 8:36 PM, Justin Martin <notifications@github.com> wrote:
> 
> I thought when you said you had a simple case, you were doing it in the context of a sample app or something simple. You could try to reproduce the issue with the test app that is contained in the KIF project, or one of the sample apps.
> 
> KIF doesn't really have a memory management model to speak of. It has no singletons, no long lived objects, and no caches. If you look at the macro definition for tester (or viewTester), it is allocating a new KIFUITestActor (or KIFUIViewTestActor) object on the stack, and that object should be destroyed when it goes out of scope. The tester objects are generally pretty lightweight though (like 80 bytes each).
> 
> The other thing that is worth mentioning is that when exceptions are thrown and caught in Objective-C, they leak memory by default unless you compile with a special clang compiler flag. You can read more about it here:
> https://www.eltima.com/dev/2014/08/11/objective-c-arc-and-exceptions/ <https://www.eltima.com/dev/2014/08/11/objective-c-arc-and-exceptions/>
AHA.  Thank you.
> Even if your code isn't explicitly using @try/@catch <https://github.com/catch> blocks, XCTest as a test framework has them. It halts test execution by throwing exceptions and then catching them in invokeTest in order to report the test as failed and run tearDown. If you have tests that are known to be failing in your test suite, any objects that are allocated and supposed to be torn down between the scope where the failure occurred and the catch happens, they'll leak.
> 
> —
> 

Do you have any insight as to why operations run while in KIF take more memory than when run in the app alone?  The part where we have a 5 MB operation balloon to a 30 MB operation when run from KIF is something I’d like to understand.

Thanks again.

**Comment by justinseanmartin** [comment]
There isn't enough information for me to know with any sort of certainty. I think you'll have to take a look at memory graph analyzer or instruments and see what the objects are and who is still holding a reference to them that make up the 25 MB.

As a complete guess though, if the objects being allocated are within tableview cells, it is possibly caused by the way KIF walks the view hierarchy. For UIKit's UITableView behavior, cells that are offscreen are intentionally not part of the UIView hierarchy so as to avoid creating lots of unnecessary stuff. For KIF, we still need to be able to match against table view cells even if they're scrolled offscreen, so we snap the table view to different scroll positions to have cells be created in order to check if they are the ones we're supposed to be matching. That being said, those cells should be cleaned up and not lead to any additional long lived objects, unless they're being created and/or held by your application itself.

You can start looking at [UIView-KIFAdditions.m#L230](https://github.com/kif-framework/KIF/blob/a877356251d4df9d0e3f62be1f97a8e1395b870c/Additions/UIView-KIFAdditions.m#L230) to see the special handling for matching against table view cells (and collection views handling is also special cased just below that).

**Comment by justinseanmartin** [comment]
One thing I noticed from playing around is that the method `-[KIFUIViewTestActor waitForView]` (or the `-[KIFUITestActor waitForViewWith...:]` variants) by returning the autoreleasing `UIView *` reference does extend the lifetime of the actor object. I don't think that should cause substantial memory growth though, because those objects are pretty small and should get cleaned up at the end of the test as long as no exceptions are thrown. 

If the lifetime of the actor being extended is a problem though, you could wrap the call to `waitForView` in an `@autoreleasepool` block to ensure it gets cleaned up immediately. 

In general though, usage of `waitForView` should be unnecessary, as calling `tap` or other actions does an implicit wait for the element to be in the view hierarchy before attempting to interact with it.
