### ISSUE TITLE
build fails for arm7 arm64

### ISSUE THREAD

**Issue by subbarao** [kif-framework/KIF#653]

**Comment by phatmann** [comment]
I am surprised to see build issues when using CocoaPods. Are you using CocoaPods 0.36 or 0.37 by any chance? I had to revert to 0.35 due to build issues in my own project.

**Comment by subbarao** [comment]
i am using 0.37. let me downgrade and see.

**Comment by phatmann** [comment]
If 0.35 works,  I would like to understand why 0.37 is failing. Let me know if you have any ideas. Unless the CocoaPods folks make a fix, we might have to fix on our end.

**Comment by phatmann** [comment]
Is this possibly a Jenkins issue?

**Comment by luoxubin** [comment]
Hi @phatmann ，Is there an other way to fake a touch event without rely on IOKit， just like the way as before #582， not use pure C private APIs. Because my app need to submit to AppStore, and need to simulate touch event in some scene. I have ask many friends and still have not work it out. Can you help me?
Many thanks.  
My email :394934942@qq.com

**Comment by billburgess** [comment]
Having same issue on 0.38.2
