### ISSUE TITLE
Will KIF support targeting elements in WKWebView?

### ISSUE THREAD

**Issue by jiacy** [kif-framework/KIF#708]
Since WKWebView has better performance than UIWebView, and is being used or planing to be used in  more and more places.  I was wondering does KIF support UI Auto Test in WKWebView. Then I saw issues #460 .
I'm trying to ask, if KIF can't do the job due to some limitations, can we leverage UI Automation APIs(like UIAutomationHelper) to do the work? or is KIF planning to support WKWebView in the near future?

Thanks a lot!

**Comment by phatmann** [comment]
@jiacy Thanks for the question. There has [been some discussion](#646) in the v4 thread about using  the new XUI layer in Xcode 7 to drive KIF, as that would give us access to WKWebView among other things. However, so far that appears to be a tough road because that library does not give us access to real UIViews, runs in another process, etc.

So the answer to your question: KIF will not support WKWebView in the near future. And unless some brave, adventurous soul ports it to XUI -- or Apple exposes WKWebView more completely via UIAccessibility -- KIF probably never will.

**Comment by jiacy** [comment]
@phatmann Thanks a lot for your answer! 
And could you give me a link for the discussion about using the new XUI layer in Xcode 7 to drive KIF, that would be really helpful :)

**Comment by phatmann** [comment]
@jiacy, in the v4 discussion there was a brief mention of the idea of using the XUI layer. But no research has been done into it yet. I really have no idea if it is possible or not.
