### ISSUE TITLE
NSInvalidArgumentException in windowsWithKeyWindow

### ISSUE THREAD

**Issue by rcrahul43** [kif-framework/KIF#732]
I am using KIF 3.0
I have an project setup with storyboard and I'm using Xcode 7.

    [tester waitForViewWithAccessibilityLabel:@"Login"];

On executing above line All exception break point takes me to 
- (NSArray *)windowsWithKeyWindow
{
    NSMutableArray *windows = self.windows.mutableCopy;
    UIWindow *keyWindow = self.keyWindow;
    if (![windows containsObject:keyWindow]) {
        [windows addObject:keyWindow];
    }
    return windows;
}

In this block the keyWindow object is nil.

**Comment by phatmann** [comment]
This means your Test Host (i.e. your app) is not initialized properly before the test starts running. Can you set a breakpoint in your app delegate's `didFinishLaunching` method and see if it runs before your test?

**Comment by whateverDude** [comment]
@phatmann I see the same issue and it's not hitting didFinishLaunching at all.  CMD-U runs my Kif test and I see the exception mentioned above.  How to resolve this? What did I set up wrong?

**Comment by whateverDude** [comment]
@bnickel :Can you please help with my setup issue above?

**Comment by whateverDude** [comment]
Please help.  I'm stuck big time...

**Comment by phatmann** [comment]
Hi @whateverDude. You said you are running into the same issue, but then you said your exception is not a `windowsWithKeyWindow` error. Should this possibly be filed a new issue?

That said, I will need to know more about your set up to help you out.

**Comment by whateverDude** [comment]
Hi @phatmann . Thanks for replying.  I do have the windowsWithKeyWindow error as I logged above.  I'm using KIF 3.3.0 and XCODE 7.1. I've setup KIF using cocoaPods using https://github.com/kif-framework/KIF#installation-with-cocoapods.  I have one test target I created.

As soon as I run my tests in XCODE (CMD-U), it tried to run my KIF test but it doesn't launch the application (instead it opens another empty appWindow) which leads to the exception below because the window is nil.

Here's my test case(just starting with KIF):

#import <UIKit/UIKit.h>
#import <XCTest/XCTest.h>
#import <KIF/KIF.h>
@interface DigiMobileiOSUITests : KIFTestCase
@end

@implementation DigiMobileiOSUITests
- (void)testSuccessfulLogin
{

// Tap home button
    [tester waitForTappableViewWithAccessibilityLabel:@"HomeButton"];
    [tester tapViewWithAccessibilityLabel:@"HomeButton"];
}
@end

**Comment by mikelupo** [comment]
This issue seems vaguely familiar. I encountered something like this in my own app under test when I first started writing UI tests for our app. 
I wonder, do the developers of the code do something different in the case that they detect that unit tests are running and hence does not load the storyboard.



	if (NSClassFromString(@"XCTest")) {
		self.window.rootViewController = [[UIViewController alloc] init];
		self.mainStoryboard = nil;
	} else {
    [self transitionToTheStoryBoard]
	}


Recall that KIF runs on top of the XCTEST apple APIs so when you run UI tests from KIF, it could trigger the alternate app UI behavior intended by devs for the running of Unit Tests.


I am also wondering if your scheme is set up properly. 
My scheme that loads the tests refers to the executable, "None". 
Said another way...
1) Edit your test scheme
2) select, "Run" 
3) for the executable field select, "None".


Hoping that this helps you.




-----Original Message-----

**Comment by whateverDude** [comment]
@mikelupo I'm not using storyboards...using nibs...I didn't have a separate scheme for test so I just created it and set the executable field to none as you indicate above in the "RUN" pane but to no avail.  Same issue.  Not sure where you want me to put the code you mentioned, inside my test case? And I have break point in my didFinishLaunching and it does not get hit...

**Comment by mikelupo** [comment]
@whateverDude, I wasn't asking you to put that code in, but instead to look/search for something like that planted by the developers to hide the UI during Unit testing. 

in your separate test target, is the build settings set to launch the host application?
Here's how to check:
In the file explorer select the project. This reveals your targets.
Select the test target. 
Select the "General" Tab.
Look for "Test Target". Make sure it's set to launch your app under test.

While you're in that UI, tap on the, "Build Phases", tab. Make sure it depends on the target for the under test in the Target Dependency section. 

If this won't work, then can you somehow scrub the project of any proprietary info, zip it up and send it to either myself or @phatmann?  I'm sure with it in our hands, we can help identify the issue.

**Comment by whateverDude** [comment]
I'm attaching a dummy project I created that shows the issue I'm having...Please take a look.
[testDynamicCells.zip](https://github.com/kif-framework/KIF/files/54138/testDynamicCells.zip)

**Comment by mikelupo** [comment]
@whateverDude I replied via email with an attachment. I don't see it here when I come to GH to review it. So I'll repost. Sorry for the SPAM if it appears mx times.

I could not integrate KIF using cocoapods. It fails miserably for me and I don't know enough about using cocoapods to know if it's me, my ruby, my network or some harrad combination of all of that.
....That said, I had to integrate KIF by hand. Which is how I am accustomed to doing it anyway.

Try the attached. It works for me insomuch that your app launches and fails a test because it could not find the accessibility label. 
I did this on Xcode 7.1.1 and one of the iPad simulators. 
"As-is", Running this on hardware will not work as-is because the bundle ID isn't set to something you can sign. That's something for you to work out and isn't a KIF related thing.

Hope this helps.

[testDynamicCells.zip](https://github.com/kif-framework/KIF/files/54479/testDynamicCells.zip)

**Comment by whateverDude** [comment]
@mikelupo Thanks a million! Maybe my issue is related to integration if KIF with cocoapods.  Now so I can do what you did into my real project.  Which directions do you recommend I follow, https://github.com/kif-framework/KIF#installation-from-github ? Apparently   https://github.com/kif-framework/KIF#installation-with-cocoapods doesn't work since that's what I followed.

**Comment by mikelupo** [comment]
@whateverDude. I don't exactly follow either of those directions, albeit what I do to include KIF is more aligned with the non-cocoapods method as you will soon see. This is because I am not allowed to use git submodule by policy.

Here's what I do. It's not the cleanest install. 
Assuming you've created a Unit Test Target. I give it a name like MyAppUITests. (Yes I did say UNIT test on purpose, not Cocoa Touch UI Tests just to be clear)

1) I clone KIF to a separate directory outside of my project.
2) In Xcode, in my app project where the tests are stored, I create a sub-folder (better known as a Group in Xcode) called, TestFrameworks
3) On my hard disc, I then create the same actual folder in the directory where my tests live.
4) I then COPY the entire KIF directory into that folder on my local disc.
5) Drag that newly copied folder over to XCode UI into the TestFrameworks folder. A wizard appears. DO NOT CHOOSE ANY TARGET CHECKBOXES. Go ahead and choose, "Copy if necessary".
6) Again In Xcode, I now click on the app project to reveal the targets.
7) Select the test target (i.e. MyAppUITests) and go into the build phases.
8) For Target dependencies, select your App Target as well as KIF Target. (2 targets in all)
9) For Link Binaries with libraries, you'll select libKif.a as well as one that's private and hidden (ioKit.framework). Because it's private (and hidden) you'll need to find this on your local hard disc, then DRAG it from a finder window into that (Link Binaries with libraries) UI. This is resident in each XCode.app you have installed. For example the folder is, /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/ioKit.framework
10) Now, in your test Target "Build Settings" tab, search for linking section. In that section you will find the entry, "Other linker flags. Give that a value of "-ObjC"  (minus the quotes). Failure to do this will result in build time errors. 
11) in my test case, I import KIF like this, 
`#import "KIF.h`
That will integrate KIF for you.
Let me know if these instructions work. Perhaps I'll update the KIF repo to include this as a method of install. Probably with a small bit of refining.

I've not gone at all into the schemes, it may be necessary to get you up and running, but is a different discussion.

**Comment by whateverDude** [comment]
@mikelupo Thanks a lot for all of your help.  Turns out the whole issue I was having is because when I created the test target, I selected "iOS UI Testing bundle" instead of "iOS Unit Testing Bundle" since I was doing UI testing not unit testing but that's what caused the issue.  So to sum up, you can use cocoapods to install as per the instructions in KIF but must use "iOS Unit testing bundle" when creating the test target.  That fixed the issue.  You pointed me to the right direction when you said use Unit Test Target.  Thanks for all of your help.

**Comment by mikelupo** [comment]
@whateverDude 
Glad to get you up and running. We hope you'll get some good use out of KIF and perhaps even contribute some code back to the community.
Enjoy!
