### ISSUE TITLE
Weak variable not nillified when deriving from KIFTestCase

### ISSUE THREAD

**Issue by Johennes** [kif-framework/KIF#739]
The following test case fails unexpectedly on the `XCTAssertNil` statement.

```
class Test2_0Tests: KIFTestCase {

    func testExample() {
        var foo: UIViewController? = UIViewController()
        weak var bar = foo
        foo = nil
        XCTAssertNil(bar)
    }

}
```

However, when I derive from `XCTestCase` directly, the test passes. The only way I found to make it pass when deriving from `KIFTestCase` is to use an explicit autorelease pool.

```
class Test2_0Tests: KIFTestCase {

    func testExample() {
        var foo: UIViewController?
        weak var bar: UIViewController?

        autoreleasepool {
            foo = UIViewController()
            bar = foo
            foo = nil
        }

        XCTAssertNil(bar)
    }

}
```

Deriving from `XCTestCase` or `KIFTestCase` should not make a difference here, or should it?

**Comment by phatmann** [comment]
KIF does use its own autorelease pools and cranks the run loop, so I imagine this might be causing the issue you are seeing. There have been various issues about memory management filed, and some (see #515) are still open. In short, it does seem like KIF is causing references to stick around too long. However, I have no easy solution to offer, since previously we had issues with values being dereferenced too early!
