### ISSUE TITLE
Insufficient permissions to create screenshot folder

### ISSUE THREAD

**Issue by vase4kin** [kif-framework/KIF#744]
Hello, guys!

Suddenly i noticed that i don't get any screenshots on test failure. I don't get them on local machine and CI as well. 

Debugging the code i found the problem, it happens on create folder part:
```
Error Domain=NSCocoaErrorDomain Code=513 "You don't have permission to save the file "Screenshots"." UserInfo={NSFilePath=Screenshots, NSUnderlyingError=0x7dde3f20 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
```

So what could it be?

My configuration:
* XCTest
* `KIF_Screenshots` env variable is set to _Screenshots_ 
* Xcode is 7.1.1
* KIF 3.3.0

Thanks!

**Comment by mikelupo** [comment]
Does this help? 

https://groups.google.com/forum/m/#!topic/kif-framework/sLls_MlJAsE

**Comment by vase4kin** [comment]
I forgot to mention that `KIF_Screenshots` env variable was set properly in the scheme run arguments.

@mikelupo I tried solution with giving extra permissions with `chmod 777` to _Screenshots_ folder, but it doesn't work, i see the same error.

**Comment by mikelupo** [comment]
That's weird because the app itself should have the ability to write to its own Documents directory. Said another way... KIF, running in the app under test's process, should have the same permissions to write to the ~/Documents directory that the app under test does. 
Also, make sure that you are indeed running the scheme. 

Do you have two schemes? One for the app and one for the tests? The way I run is using two. My tests scheme (which builds KIF and my test cases) depends on the app scheme.
FYI I do not integrate KIF using cocoapods as we are not allowed to have external build time dependencies.

**Comment by vase4kin** [comment]
Yeah, it sounds very strange that app process don't have permissions. 
The thing is that i used to take screenshots before and i don't clearly understand what happened actually. 
Btw what's your setup? Are you able to take screenshots?

**Comment by vase4kin** [comment]
Btw, it solved. The problem was in env variable, it wasn't in upper case.
