### ISSUE TITLE
SFSafariViewController Support

### ISSUE THREAD

**Issue by sirnacnud** [kif-framework/KIF#751]
Has anyone been able to get KIF to interact with a SFSafariViewController? I haven't had any luck and am wondering if it is possible.

**Comment by phatmann** [comment]
I doubt it is possible, since WKWebView was not accessible, either.

**Comment by emersonmalca** [comment]
any hints on how you would go about testing Facebook integration then? Its authentication dialog is presented in a SafariViewController instance

**Comment by mikelupo** [comment]
Can you even see accessibility labels on the UI elements in that view?

**Comment by bnickel** [comment]
It's not really possible with KIF since SFSafariViewController uses a remote view outside of the application process and memory space.  My philosophy has always been to mock those external constraints, e.g., create a test step that calls `application:openURL:options:` with a recent valid login response URL you grab while debugging your app.

I believe `UIAApplication` should be able to access it but that would involve rewriting or supplementing large parts of KIF to use it.
