### ISSUE TITLE
Test UI thread safety

### ISSUE THREAD

**Issue by nhgrif** [kif-framework/KIF#804]
Per [this gist](https://gist.github.com/steipete/5664345), it seems it's possible to detect at least a large portion of instances of UIKit calls being made on background threads.  

Would it be possible to incorporate this detection into KIF resulting in failed tests when detected?

**Comment by phatmann** [comment]
Neat find. Can you give an example where this would be used within a KIF test?

**Comment by nhgrif** [comment]
I don't think it is something that the end user should have to explicitly write.  Running UI on the background should _never_ be okay, so any KIF test method that _can_ fail, _should_ fail if during that test, it detected UIKit calls on the background.

**Comment by nhgrif** [comment]
In a different, but perhaps similar manner, it might also be neat if KIF noticed autolayout constraints breaking and automatically failed tests if a constraint broke during the test.

**Comment by mikelupo** [comment]
If KIF did that my tests would never pass in the early stages of code development.

**Comment by RoyalPineapple** [comment]
I agree with Mike its important to be able to use KIF during development. I don't believe we need KIF to become a one-stop-shop for all things testing (despite how helpful they might be).

I'd personally prefer to focus KIF on being the "driver" for your app and allow it to be used in conjunction with other testing libraries which can add the kind of functionality you're describing here.

**Comment by bnickel** [comment]
As a note, background thread calls are not so cut and dry.  I have several views I use for measurements on a background sequential queue.  Because they don't interact the main view hierarchy and are single threaded in their own context they're *relatively* safe.

Similarly, UIKit will sometimes make thread unsafe calls.  WebKit for example creates buttons on a background thread when it encounters a media element, triggering `UIView.setAnimationsEnabled(_:)`. (rdar://20314684)

**Comment by phatmann** [comment]
So the consensus seems to be that detecting illegal calls to UIKit and constraint conflicts are great ideas, but outside of KIF's purview. Perhaps @nhgrif you might want to author a KIF or XCTest add-ons to do this, since I imagine lots of folks would find them useful.
