### ISSUE TITLE
Can't tap buttons in Apple Pay view

### ISSUE THREAD

**Issue by SquaredTiki** [kif-framework/KIF#826]
KIF seems unable to tap the `Pay with Passcode` or `Cancel` buttons in the Apple Pay view that appears in the simulator when prompting for Apple Pay authorisation. 

![simulator screen shot 29 mar 2016 17 34 58](https://cloud.githubusercontent.com/assets/146159/14115836/a56c81c4-f5d4-11e5-827e-5a1948aecd91.png)

**Comment by mikelupo** [comment]
Curious ...Did it ever work?

**Comment by SquaredTiki** [comment]
I'm not sure, this is my first attempt at using KIF with Apple Pay.

**Comment by RoyalPineapple** [comment]
SquaredTiki I believe that is a system-provided dialog which puts your app in a background state when its active, so it would make sense that KIF (running in the app process) cant act on this view. 

I'm not sure if it will help in your specific circumstance but one approach that is used here is to use a different interface for faking Apple Pay so that you don't actually involve the system at all during your tests. See: https://github.com/stripe/ApplePayStubs

**Comment by mikelupo** [comment]
KIF cannot tap any UI outside of its process.
