### ISSUE TITLE
BDD support for KIF

### ISSUE THREAD

**Issue by CurlyHeir** [kif-framework/KIF#895]
Hi, 
i created addition for KIF, small library for ~BDD, should i create pull request to KIF? 
@phatmann @bnickel 
Take a look:
https://github.com/AzimoLabs/SimpleBDD

**Comment by phatmann** [comment]
@CurlyHeir: your library looks nice and quite useful. However, it would not make sense to pull it into KIF, since it sits on top of KIF and provides functionality that only some users would want. Instead, I would suggest one of two ideas:

1. Rename it to something like "KIF-BDD", so its purpose is more obvious.
1. Lobby to get it added into the kif-framework organization, alongside KIF, AMY, and Lela. You would need to convince @bnickel...and choose a Futurama character :-)

**Comment by CurlyHeir** [comment]
good to hear, i will decide latter - after library cleanup. 
Thx for info.
