### ISSUE TITLE
enterTextIntoCurrentFirstResponder crashes when entering long text into UITextField which is "Secure Text Entry"

### ISSUE THREAD

**Issue by nkonforty** [kif-framework/KIF#909]
KIFTypist crashes when entering long text (it crashes on letter number 26) into Secure Text Entry. 
When changing the UITextField to be not secure the test passes successfully.
![screen shot 2016-09-12 at 10 21 23 am](https://cloud.githubusercontent.com/assets/14818973/18427969/ee7a37ee-78d3-11e6-8877-ff2b407cb1d1.png)

**Comment by mikelupo** [comment]
Hi. Thanks for using KIF.

Is it possible you could put together a small single view app that highlights the issue? If we can reliably reproduce it, we stand a better chance of a resolution.
Also, what version of XCode, What device/simulator and iOS version?

Thanks!

**Comment by nkonforty** [comment]
[SecureTestEntry.zip](https://github.com/kif-framework/KIF/files/467423/SecureTestEntry.zip)

please use the attach project and run the test: "testLongPassword"
I'm using Xcode 8 with simulator iPhone 6s iOS 10 
(it also happened on Xcode 8 beta 6)

**Comment by mikelupo** [comment]
Thanks for doing that.
Are you aware that the app hangs when you type the text manually? For me, KIF just hangs waiting for something to happen.

I have a workaround.
Go into the storyboard editor for the text field, tap the attributes tab, and uncheck the checkbox, "Adjust to fit" (it's just below the "Min Font Size") attribute. 
IMHO this is an Apple bug since it hangs the UI. Wouldn't hurt for you to file a RADAR on it. 
With that checkbox off, I am able to run your test manually and through KIF as well.

Feel free to reopen this if you think we need to take a harder look at KIF. 

Thanks!
