### ISSUE TITLE
Can KIF  assert what was opened with Safari from ios app??

### ISSUE THREAD

**Issue by bnimmagadda** [kif-framework/KIF#945]
We have a ios app which launches browser.I would like to assert things within browser.
Is there a possibility to do that with KIF.

Thanks for your help

**Comment by justinseanmartin** [comment]
`UIApplication-KIFAdditions.m` has a method:

```
+ (void)startMockingOpenURLWithReturnValue:(BOOL)returnValue;
```

For us, we just check the URL is what we expected it to be, but don't load it. This is because it doesn't directly influence the behavior of the application.

If you are navigated out of the application to Safari, the KIF tests will stop running. This is a limitation of the way that XCTest runs.

I haven't tried it before, but you should potentially be able to check that the `lastOpenedUrl` gets set to the value you're expecting and then load it within a `WKWebView` in a window inside of your application. You'd have to expose some UI control or API to dismiss the `WKWebView` when you're done interacting with it.
