### ISSUE TITLE
Unable to tap table view cells that are under a toolbar

### ISSUE THREAD

**Issue by hiltonc** [kif-framework/KIF#953]
I have a `UITableViewController` subclass in a `UINavigationController` with `toolbarHidden = false`. When I use KIF to tap on a cell that is currently under the toolbar, KIF doesn't scroll and it fails. I assume this is because KIF thinks the cell is already on screen, but is unable to touch it because it is obscured by the toolbar.

**Comment by justinseanmartin** [comment]
Yea, the table view handling definitely has a couple bugs in there. In the past, I've worked around them on a case-by-case rather than reworking the KIF tableview logic. The bug is likely in here:

https://github.com/kif-framework/KIF/blob/master/Additions/UIView-KIFAdditions.m#L227

If you'd like to dig around for your particular scenario and see if there is something that can be fixed, that would be great.

**Comment by hiltonc** [comment]
The problem was elsewhere, but you succeeded in getting me to solving it myself 👍
