### ISSUE TITLE
Any way I can use KIF to uncheck the connect Hardware Keyboard option while running my UITests ?

### ISSUE THREAD

**Issue by anshu10165** [kif-framework/KIF#968]
Is there a way I can use in KIF to uncheck the connect Hardware Keyboard option while running my UITests.(iOS Simulator-> Hardware-> Keyboard -> Uncheck the Connect Hardware Keyboard)

Only way I could find till now is to add the below line in shell script.
**defaults write com.apple.iphonesimulator ConnectHardwareKeyboard -bool no**

Above works fine, since I have added xcode build command in shell file, however when it comes to running the test through xcode IDE, I need to manually uncheck the Connect Hardware Keyboard option in the simulator, which I want to avoid.

Any help would be much appreciated here.

**Comment by mikelupo** [comment]
When my tests are running locally in Xcode, and I observe that the keyboard isn't coming up when I need it to, I quickly toggle Command-Shift-k. Then it seems to work going forward for both UI automation as well as manual. 

I don't think KIF can do it, though I admit I have not tried.


Hope this helps.
Mike




-----Original Message-----

**Comment by anshu10165** [comment]
Thanks for the comment @mikelupo. I was going through some article/forums as well, and looks like its tough to control "core iOS simulator actions " through a test framework. Not sure if thats completely true.

**Comment by justinseanmartin** [comment]
So the problem is that the setting is read from defaults at startup, but it seems like it is then cached. It would be pretty easy to add a script in your test target with:

```
defaults write com.apple.iphonesimulator ConnectHardwareKeyboard -bool no
killall Simulator
```

This seems like it'd ensure that when the simulator app is relaunched, it should have the right setting, but it might take extra time to relaunch the simulator over and over again each time you CMD+U.

Alternatively, you could just fail the build if the setting isn't set the way you expect and have it be a manual intervention to ensure the settings are set appropriately. I think this is probably the most straightforward approach to ensure consistent behavior.

Another option would be to toggle it with an apple script, such as:
https://github.com/paypal/Illuminator/blob/master/gem/resources/scripts/set_hardware_keyboard.applescript

I don't think this should be up to KIF though, I'd leave this responsibility up to people integrating the test framework into their apps as to what and how they want this done.

**Comment by joquerod** [comment]
Tested with Xcode 10.1
I tried different approaches but none of them solve how to get the simulator UDID
```
#Find the UDID of the booted simulator
#And use PlistBuddy to change the flag to true or false
#Set the variable useHardwareKeyboard with the desired result
#Kill the simulator
useHardwareKeyboard=false
UDID=$(xcrun simctl list devices | grep "(Booted)" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})")
/usr/libexec/PlistBuddy -c "Set :DevicePreferences:$UDID:ConnectHardwareKeyboard ${useHardwareKeyboard}" ~/Library/Preferences/com.apple.iphonesimulator.plist
killall "Simulator"
```

You can also verify these changes.

Find your simulator UDID: (More here: https://nshipster.com/simctl/)
```
xcrun simctl list devices | grep "(Booted)" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})"
```

Run one of these commands and find your changes based on the UDID from above:
```
defaults read com.apple.iphonesimulator
#OR
open ~/Library/Preferences/com.apple.iphonesimulator.plist
```

**Comment by justinseanmartin** [comment]
Yea, I think you'd have to do this in a script phase or scheme test pre-action, but I'm not sure if you'd have access to the booted simulator at that point. There may be enough information in the environment variables to discern what destination is being used to be able to guess which simulator will get booted. I guess technically you could do it for all simulator UUIDs if you wanted to be safe, as writing to defaults should generally be pretty fast.
