### ISSUE TITLE
waitForViewWithAccessibilityLabel keeps view hidden behind navbar

### ISSUE THREAD

**Issue by LMojica** [kif-framework/KIF#975]
My app has a floating navigation bar on the bottom of the screen. When I call waitForTappableViewWithAccessibilityLabel on a label that requires scrolling of the screen, KIF will correctly scroll to the spot where the label would have been visible on the screen, but since I have a floating navbar on the bottom, the label is actually hidden behind the navbar. This results in a time out error with the message `Accessibility element with label "expand-button" is not tappable. It may be blocked by other views.`

Is there a way to have KIF keep scrolling until the label is no longer hidden by the navbar? Or having a method that will center a label on the screen?

**Comment by phatmann** [comment]
I am not sure what behavior you are looking for. How would KIF know to keep scrolling?

**Comment by LMojica** [comment]
If KIF isn't able to know that a label is being blocked, is it possible to have methods that allow us to specify where to place the label on the screen? I see that now, KIF will scroll until the view containing the label is at the edge of screen. Can there be a method that makes KIF center the view on the screen rather than at the edge?

**Comment by justinseanmartin** [comment]
@LMojica - When you say floating navigation bar, what do you mean by that? The scrollable view containing the element you want to tap on extends below the navbar? I assume there an intentional reason for that, rather than sizing the scrollable view appropriately?

It seems like some of the logic in `UIAccessibilityElement-KIFAdditions.m` could be adjusted to make it work. We'd need to determine the non-obstructed region of the scrollView (as in not obstructed by other views) when attempting to scroll its child into view.

This method currently automatically does the scrolling if a matching element is found:

```
+ (UIView *)viewContainingAccessibilityElement:(UIAccessibilityElement *)element tappable:(BOOL)mustBeTappable error:(NSError **)error;
```

Pull requests are welcome if you wanted to try working on a generic fix for this issue.

As far as making a fix in your code without touching KIF code itself, you could use `[viewTester waitForView]` to capture the matched view object, walk up to the superviews to the UIScrollView, then explicitly invoke `setContentOffset:` on it to move it onscreen.

**Comment by LMojica** [comment]
I ended doing what @justinseanmartin recommended as a workaround for this issue. I will close this issue now.
